version: 2
jobs: 
  deploy_staging:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
            fingerprints:
              - $SSH_HOST_FINGERPRINT_STAGING
      - run:
          name: SSH Deploy Staging
          command: |
              ssh $SSH_USER@$SSH_HOST_STAGING bash -c '
                cd /var/www/html/healthport_patient_frontend
                sudo git fetch
                sudo git checkout staging
                sudo git pull'
workflows:
  version: 2
  deploy:
     jobs:
      - deploy_staging:
          filters:
            branches:
              only:
                - staging